server:
  port: 8086
spring:
  application:
    name: aurora-backend
  jpa:
    show-sql: false
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect
  jmx:
    enabled: false
  datasource:
    url: jdbc:mysql://192.168.0.50:3306/aurora?allowPublicKeyRetrieval=true&sslMode=DISABLED
    username: root
    password: password
eureka:
  instance:
    prefer-ip-address: true
  client:
    service-url:
      defaultZone: http://localhost:8081/eureka
    register-with-eureka: true

logging:
  pattern:
    level: DEBUG
